In [43]:
pip install pandas

Requirement already satisfied: pandas in c:\users\abdul\anaconda3\lib\site-packages (2.3.3)
Requirement already satisfied: numpy>=1.26.0 in c:\users\abdul\anaconda3\lib\site-packages (from pandas) (2.3.5)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\abdul\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\abdul\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\abdul\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\abdul\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [44]:
import pandas as pd
import numpy as np

In [45]:
s1 = pd.Series(data=[10,20,30,40,50])
s1

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [46]:
s2 = pd.Series(data=[100,200,300,400,500])
s2

0    100
1    200
2    300
3    400
4    500
dtype: int64

In [47]:
s3 = pd.Series(data=[1000,2000,3000,4000,5000],index=list('vwxyz'))
s3

v    1000
w    2000
x    3000
y    4000
z    5000
dtype: int64

In [48]:
df = pd.DataFrame({'C1':s2, 'C2':s2})
df

    C1   C2
0  100  100
1  200  200
2  300  300
3  400  400
4  500  500

In [49]:
df = pd.DataFrame(data=np.random.randint(1,100,size=(1000,5)), columns=list('abcde'))
df

      a   b   c   d   e
0     7  21  24   7  82
1    77  44  53  54  26
2    28  84  15  69  95
3    90  25  48  21  67
4    87  38  46  77  88
..   ..  ..  ..  ..  ..
995  32  82  96  99  37
996  35  49  75  64  25
997  41  63  84  21  72
998  19  73  60  64  68
999  22  51  90  88  54

[1000 rows x 5 columns]

In [50]:
dataset = pd.read_csv(r"C:\Users\Abdul\OneDrive\Documents\Python\Dataset\Car.csv")
dataset

    Age  Income  Car
0    28   37000    0
1    27   88000    0
2    28   59000    0
3    32   86000    0
4    33  149000    1
..  ...     ...  ...
95   28   89000    0
96   34   43000    0
97   30   79000    0
98   20   36000    0
99   26   80000    0

[100 rows x 3 columns]

In [51]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Age     100 non-null    int64
 1   Income  100 non-null    int64
 2   Car     100 non-null    int64
dtypes: int64(3)
memory usage: 2.5 KB

In [52]:
dataset.head()

   Age  Income  Car
0   28   37000    0
1   27   88000    0
2   28   59000    0
3   32   86000    0
4   33  149000    1

In [53]:
dataset.tail()

    Age  Income  Car
95   28   89000    0
96   34   43000    0
97   30   79000    0
98   20   36000    0
99   26   80000    0

In [54]:
dataset.Car.value_counts()

Car
0    93
1     7
Name: count, dtype: int64

In [55]:
dataset.rename(columns={'Car' : 'Target'})

    Age  Income  Target
0    28   37000       0
1    27   88000       0
2    28   59000       0
3    32   86000       0
4    33  149000       1
..  ...     ...     ...
95   28   89000       0
96   34   43000       0
97   30   79000       0
98   20   36000       0
99   26   80000       0

[100 rows x 3 columns]

In [56]:
dataset

    Age  Income  Car
0    28   37000    0
1    27   88000    0
2    28   59000    0
3    32   86000    0
4    33  149000    1
..  ...     ...  ...
95   28   89000    0
96   34   43000    0
97   30   79000    0
98   20   36000    0
99   26   80000    0

[100 rows x 3 columns]

In [57]:
dataset.rename(columns={'Car':'Target'},inplace=True)
dataset

    Age  Income  Target
0    28   37000       0
1    27   88000       0
2    28   59000       0
3    32   86000       0
4    33  149000       1
..  ...     ...     ...
95   28   89000       0
96   34   43000       0
97   30   79000       0
98   20   36000       0
99   26   80000       0

[100 rows x 3 columns]

In [58]:
dataset.columns

Index(['Age', 'Income', 'Target'], dtype='object')

In [59]:
dataset[['Age','Target']]

    Age  Target
0    28       0
1    27       0
2    28       0
3    32       0
4    33       1
..  ...     ...
95   28       0
96   34       0
97   30       0
98   20       0
99   26       0

[100 rows x 2 columns]

In [60]:
dataset.loc[50]

Age          20
Income    74000
Target        0
Name: 50, dtype: int64

In [61]:
dataset.loc[50:60]

    Age  Income  Target
50   20   74000       0
51   26   15000       0
52   41   45000       0
53   31   76000       0
54   36   50000       0
55   40   47000       0
56   31   15000       0
57   46   59000       0
58   29   75000       0
59   26   30000       0
60   32  135000       1

In [62]:
dataset[dataset['Income']>100000]

    Age  Income  Target
4    33  149000       1
38   30  107000       1
60   32  135000       1
69   29  148000       1
72   34  115000       0
73   26  118000       0
83   32  117000       1

In [63]:
import pandas as pd
example = pd.read_csv(r"C:\Users\Abdul\OneDrive\Documents\Python\Dataset\abc.csv")
example

  iteams  price
0      A   70.0
1      B    NaN
2      C   50.0
3      D    NaN
4      E   40.0
5      F   32.0
6      G   45.0
7      H   69.0
8      I    NaN
9      J    NaN

In [64]:
example['price'].notnull()

0     True
1    False
2     True
3    False
4     True
5     True
6     True
7     True
8    False
9    False
Name: price, dtype: bool

In [65]:
example[example['price'].isnull()]

  iteams  price
1      B    NaN
3      D    NaN
8      I    NaN
9      J    NaN

In [66]:
example['price'].fillna(example['price'].max())

0    70.0
1    70.0
2    50.0
3    70.0
4    40.0
5    32.0
6    45.0
7    69.0
8    70.0
9    70.0
Name: price, dtype: float64

In [67]:
example['price'] = example['price'].fillna(example['price'].std())
example

  iteams      price
0      A  70.000000
1      B  15.517732
2      C  50.000000
3      D  15.517732
4      E  40.000000
5      F  32.000000
6      G  45.000000
7      H  69.000000
8      I  15.517732
9      J  15.517732

In [68]:
example['price'] = example['price'].fillna(example['price'].min())
example

  iteams      price
0      A  70.000000
1      B  15.517732
2      C  50.000000
3      D  15.517732
4      E  40.000000
5      F  32.000000
6      G  45.000000
7      H  69.000000
8      I  15.517732
9      J  15.517732

In [69]:
example['price'] = example['price'].fillna(example['price'].max())
example

  iteams      price
0      A  70.000000
1      B  15.517732
2      C  50.000000
3      D  15.517732
4      E  40.000000
5      F  32.000000
6      G  45.000000
7      H  69.000000
8      I  15.517732
9      J  15.517732

In [70]:
df.drop(['b'],axis='columns')

      a   c   d   e
0     7  24   7  82
1    77  53  54  26
2    28  15  69  95
3    90  48  21  67
4    87  46  77  88
..   ..  ..  ..  ..
995  32  96  99  37
996  35  75  64  25
997  41  84  21  72
998  19  60  64  68
999  22  90  88  54

[1000 rows x 4 columns]

In [71]:
df

      a   b   c   d   e
0     7  21  24   7  82
1    77  44  53  54  26
2    28  84  15  69  95
3    90  25  48  21  67
4    87  38  46  77  88
..   ..  ..  ..  ..  ..
995  32  82  96  99  37
996  35  49  75  64  25
997  41  63  84  21  72
998  19  73  60  64  68
999  22  51  90  88  54

[1000 rows x 5 columns]

In [72]:
df.drop(['b'],axis='columns',inplace=True)
df

      a   c   d   e
0     7  24   7  82
1    77  53  54  26
2    28  15  69  95
3    90  48  21  67
4    87  46  77  88
..   ..  ..  ..  ..
995  32  96  99  37
996  35  75  64  25
997  41  84  21  72
998  19  60  64  68
999  22  90  88  54

[1000 rows x 4 columns]

In [82]:
data1 = pd.DataFrame(data=np.random.randint(1,100,size=(100,4)), columns=list('abcd'))

In [83]:
data2 = pd.DataFrame(data=np.random.randint(1,100,size=(100,3)), columns=list('xyz'))

In [84]:
data1

     a   b   c   d
0   80  84  45  76
1   95  25  33  37
2   33  45  27  56
3   32  49  47  56
4   20  50  50  47
..  ..  ..  ..  ..
95  41  23  66  11
96  23  54  12  45
97  78  37  53  90
98   4  10  52  33
99  54  32   2  66

[100 rows x 4 columns]

In [89]:
(data2)

     x   y   z
0   24   5  45
1   15  99  74
2   11  73  58
3   24  85  55
4   39  69  23
..  ..  ..  ..
95  63  69  13
96  91  78  79
97  68  23  61
98  41  68  73
99  47  34  62

[100 rows x 3 columns]

In [81]:
 data1.append(data2) # We cannot added DataFrame

AttributeError: 'DataFrame' object has no attribute 'append'

In [86]:
data3 = pd.DataFrame(data=np.random.randint(1,100,size=(100,3)), columns=list('abc'))

In [87]:
data4 = pd.DataFrame(data=np.random.randint(1,100,size=(100,3)), columns=list('ayz'))

In [90]:
data3.merge(data4, on='a')

      a   b   c   y   z
0    42  70   9  37  98
1    42  70   9  61  53
2    42  70   9  91  30
3     5  62  75  34  36
4    71  95  87  64  71
..   ..  ..  ..  ..  ..
96    8  85  61  28  88
97    8  85  61  99  30
98    8  85  61  45  63
99   73  49  57  88  40
100   7  49  84  30  21

[101 rows x 5 columns]

In [ ]:
# 11 50 74 data3
# 11 54 36 data4